"""adicionar ocupa_grade e tornar horario opcional

Revision ID: 1da8c2fdc146
Revises: a6d5f112e27f
Create Date: 2026-08-08 18:21:09.186479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1da8c2fdc146'
down_revision: Union[str, Sequence[str], None] = 'a6d5f112e27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('ocupa_grade', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('oferta', 'dia_semana',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oferta', 'horario_inicio',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('oferta', 'horario_fim',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oferta', 'horario_fim',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('oferta', 'horario_inicio',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('oferta', 'dia_semana',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('disciplina', 'ocupa_grade')
    # ### end Alembic commands ###
