"""criar tabelas iniciais

Revision ID: a6d5f112e27f
Revises: 
Create Date: 2026-08-04 16:14:15.815670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d5f112e27f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('unidade_carga', sa.String(), nullable=False),
    sa.Column('total_carga', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriz_id'), 'matriz', ['id'], unique=False)
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_aluno_id'), 'aluno', ['id'], unique=False)
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('periodo_sugerido', sa.Integer(), nullable=False),
    sa.Column('carga', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplina_id'), 'disciplina', ['id'], unique=False)
    op.create_table('aluno_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluno_disciplina_id'), 'aluno_disciplina', ['id'], unique=False)
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(), nullable=False),
    sa.Column('professor', sa.String(), nullable=True),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oferta_id'), 'oferta', ['id'], unique=False)
    op.create_table('pre_requisito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('disciplina_requisito_id', sa.Integer(), nullable=True),
    sa.Column('natureza', sa.String(), nullable=True),
    sa.Column('valor_minimo', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['disciplina_requisito_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_requisito_id'), 'pre_requisito', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_requisito_id'), table_name='pre_requisito')
    op.drop_table('pre_requisito')
    op.drop_index(op.f('ix_oferta_id'), table_name='oferta')
    op.drop_table('oferta')
    op.drop_index(op.f('ix_aluno_disciplina_id'), table_name='aluno_disciplina')
    op.drop_table('aluno_disciplina')
    op.drop_index(op.f('ix_disciplina_id'), table_name='disciplina')
    op.drop_table('disciplina')
    op.drop_index(op.f('ix_aluno_id'), table_name='aluno')
    op.drop_table('aluno')
    op.drop_index(op.f('ix_matriz_id'), table_name='matriz')
    op.drop_table('matriz')
    # ### end Alembic commands ###
